[env:esp32-p4-eth]
platform = espressif32
board = esp32-p4-eth
framework = arduino
monitor_speed = 115200
lib_deps = 
    ESP32WebServer
    ArduinoJson
    ETH
    WiFi
    ESPmDNS
    HTTPClient
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_ESP_LOG
    -DCONFIG_LOG_DEFAULT_LEVEL_DEBUG
    -DETH_PHY_TYPE=ETH_PHY_LAN8720
    -DETH_PHY_ADDR=0
    -DETH_PHY_MDC_PIN=23
    -DETH_PHY_MDIO_PIN=18
    -DETH_PHY_POWER_PIN=-1
    -DETH_CLK_MODE=ETH_CLK_GPIO0_IN

upload_speed = 921600
monitor_filters = esp32_exception_decoder
