[env:esp32-p4-eth]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    ESP32WebServer
    ArduinoJson
    ETH
    ESPmDNS
    HTTPClient
    NTPClient
    Adafruit SSD1306
    Adafruit GFX Library
    Adafruit BusIO
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_ESP_LOG
    -DCONFIG_LOG_DEFAULT_LEVEL_DEBUG
    -DETH_PHY_TYPE=ETH_PHY_IP101
    -DETH_PHY_ADDR=1
    -DETH_PHY_MDC_PIN=31
    -DETH_PHY_MDIO_PIN=52
    -DETH_PHY_POWER_PIN=-1
    -DETH_CLK_MODE=ETH_CLOCK_GPIO0_IN
    -DCONFIG_ETH_ENABLED=1
    -DCONFIG_ETH_SPI_EMAC_ENABLED=0
    -DCONFIG_ETH_USE_ESP32_EMAC=1

upload_speed = 921600
monitor_filters = esp32_exception_decoder
